services:
  - type: web
    name: Bounceland-food-bot   # <- hier muss dein Render-Service-Name stehen
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: RENDER_URL
        value: "https://bounceland-food-bot.onrender.com"
